/**
 * Gear Embedding Utility
 *
 * Loads pre-computed embeddings from gear-embeddings.json (generated by
 * `npm run generate-embeddings`). Falls back to runtime API generation
 * if the file hasn't been generated yet.
 */

import { GoogleGenerativeAI } from "@google/generative-ai";
import { gearDatabase, CATEGORY_LABELS, type GearItem } from "@/data/gear-database";

// Pre-computed embeddings (generated at build time via scripts/generate-embeddings.mjs)
import precomputedEmbeddings from "@/data/gear-embeddings.json";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

/** Cached embeddings: Map<gearId, float[]> */
let embeddingCache: Map<string, number[]> | null = null;

/**
 * Build a text representation of a gear item optimized for embedding.
 * Includes all semantically meaningful fields so the embedding captures
 * the item's use cases, not just its name.
 */
export function buildItemText(item: GearItem): string {
  const parts: string[] = [
    `${item.brand} ${item.name}`,
    CATEGORY_LABELS[item.category],
    item.subcategory || "",
    item.tier,
    `${item.weightOz}oz`,
    `$${item.priceUsd}`,
    item.description,
  ];

  // Shelter context
  if (item.shelterType) parts.push(`shelter type: ${item.shelterType}`);
  if (item.capacity) parts.push(`${item.capacity}-person`);
  if (item.seasons) parts.push(`${item.seasons}-season`);
  if (item.setupType) parts.push(item.setupType);
  if (item.fabric) parts.push(item.fabric);

  // Sleep system context
  if (item.tempRating != null) parts.push(`${item.tempRating}°F rating`);
  if (item.fillType) parts.push(item.fillType);
  if (item.fillPower) parts.push(`${item.fillPower} fill power`);
  if (item.rValue != null) parts.push(`R-value ${item.rValue}`);
  if (item.sleepStyle) parts.push(item.sleepStyle);

  // Pack context
  if (item.volume) parts.push(`${item.volume}L`);
  if (item.frameType) parts.push(item.frameType);
  if (item.maxCarryWeight) parts.push(`carries ${item.maxCarryWeight}lbs`);

  // Clothing context
  if (item.waterproof) parts.push("waterproof");
  if (item.fabricTech) parts.push(item.fabricTech);
  if (item.hoodType) parts.push(item.hoodType);

  // Kitchen context
  if (item.fuelType) parts.push(`${item.fuelType} fuel`);

  // Electronics context
  if (item.lumens) parts.push(`${item.lumens} lumens`);
  if (item.batteryType) parts.push(item.batteryType);

  return parts.filter(Boolean).join(". ");
}

/**
 * Generate embeddings for a batch of texts using Gemini embedding API.
 * Only used as a fallback if pre-computed embeddings are unavailable.
 */
async function batchEmbed(texts: string[]): Promise<number[][]> {
  const model = genAI.getGenerativeModel({ model: "gemini-embedding-001" });
  const batchSize = 100;
  const allEmbeddings: number[][] = [];

  for (let i = 0; i < texts.length; i += batchSize) {
    const batch = texts.slice(i, i + batchSize);
    const result = await model.batchEmbedContents({
      requests: batch.map((text) => ({
        content: { role: "user", parts: [{ text }] },
      })),
    });
    allEmbeddings.push(...result.embeddings.map((e) => e.values));
  }

  return allEmbeddings;
}

/**
 * Load the embedding cache.
 *
 * Priority:
 * 1. In-memory cache (instant, already loaded)
 * 2. Pre-computed JSON file from build step (no API call needed)
 * 3. Runtime API generation (fallback, expensive)
 */
export async function getEmbeddingCache(): Promise<Map<string, number[]>> {
  if (embeddingCache) return embeddingCache;

  // Try loading pre-computed embeddings
  const data = precomputedEmbeddings as Record<string, number[]>;
  if (data && Object.keys(data).length > 0) {
    const cache = new Map<string, number[]>();
    for (const [id, embedding] of Object.entries(data)) {
      cache.set(id, embedding);
    }
    embeddingCache = cache;
    return cache;
  }

  // Fallback: generate at runtime (expensive, first request only)
  console.warn("[gear-embeddings] No pre-computed embeddings found. Generating at runtime...");
  const texts = gearDatabase.map(buildItemText);
  const embeddings = await batchEmbed(texts);

  const cache = new Map<string, number[]>();
  gearDatabase.forEach((item, idx) => {
    cache.set(item.id, embeddings[idx]);
  });

  embeddingCache = cache;
  return cache;
}

/**
 * Embed a single query string for comparison against cached gear embeddings.
 */
export async function embedQuery(query: string): Promise<number[]> {
  const model = genAI.getGenerativeModel({ model: "gemini-embedding-001" });
  const result = await model.embedContent({
    content: { role: "user", parts: [{ text: query }] },
  });
  return result.embedding.values;
}

/**
 * Cosine similarity between two vectors.
 */
export function cosineSimilarity(a: number[], b: number[]): number {
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  return dot / (Math.sqrt(normA) * Math.sqrt(normB));
}
